spring.application.name=obra-1
server.port=9091
spring.sql.init.mode=never
spring.profiles.active=dev


# ---------------- Configuração de banco ----------------
#spring.datasource.url=jdbc:postgresql://localhost:5432/pizzastock
#spring.datasource.username=postgres
#spring.datasource.password=3108

# ---------------- JPA / Hibernate ----------------

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.fail-on-empty-beans=false

# ---------------- JWT ----------------
jwt.secret=TroquePorUmaChave256bitsSeguraAqui1234567890123456

# 86400 segundos = 24h
jwt.expiration=86400

# ---------------- Logging SQL (opcional) ----------------
logging.level.org.hibernate.SQL=debug

#----------------- Config de Email --------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pedroh.cler@gmail.com
spring.mail.password=jwvr elvf ejuy ebij
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.from=pedroh.cler@gmail.com
