spring.datasource.url=jdbc:postgresql://ep-autumn-forest-adbn9tuv-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_iwQ7T9IpJnZe
spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect