spring.application.name=obra-1
server.port=9090

# ---------------- Configuração de banco ----------------
spring.datasource.url=jdbc:postgresql://localhost:5432/pizzastock
spring.datasource.username=postgres
spring.datasource.password=3108

# ---------------- JPA / Hibernate ----------------

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.fail-on-empty-beans=false

# ---------------- JWT ----------------
jwt.secret=TroquePorUmaChave256bitsSeguraAqui1234567890123456
jwt.expiration=86400     # segundos (24h)

# ---------------- Logging SQL (opcional) ----------------
logging.level.org.hibernate.SQL=debug

